import type { ModuleConfig, FieldConfig } from "@/lib/modules";
import {
  allocationFields,
  recoverySchemas,
  type RecoveryTable,
} from "./schemas";

const notes: FieldConfig = {
  name: "notes",
  label: "Notes",
  type: "textarea",
  fullWidth: true,
};
function config(
  table: RecoveryTable,
  title: string,
  singular: string,
  fields: FieldConfig[],
  defaults: Record<string, unknown>,
  columns: string[],
): ModuleConfig {
  return {
    key: table,
    route: "/finances",
    table,
    schemaKey: table,
    schema: recoverySchemas[table],
    title,
    description: "Keep amounts current. Store partial account references only.",
    addLabel: `Add ${singular}`,
    emptyTitle: `No ${title.toLowerCase()} yet`,
    emptyDescription: `Add your first ${singular.toLowerCase()}.`,
    viewModes: ["list"],
    defaultView: "list",
    columns,
    fields: [...fields, notes],
    sensitive: true,
    privacyFields: columns,
    defaultValues: defaults,
  };
}

export const recoveryConfigs = {
  recoveryPlan: config(
    "recovery_plans",
    "Recovery plan",
    "Recovery Plan",
    [
      { name: "name", label: "Plan name", type: "text", required: true },
      {
        name: "monthly_income",
        label: "Monthly take-home income",
        type: "currency",
        required: true,
      },
      ...allocationFields.map(
        ([name, label]): FieldConfig => ({
          name,
          label,
          type: "currency",
          required: true,
        }),
      ),
      { name: "reserve_target", label: "Reserve target", type: "currency" },
      { name: "reserve_saved", label: "Reserve saved", type: "currency" },
      { name: "score", label: "Credit score (optional)", type: "number" },
      { name: "score_model", label: "Bureau and scoring model", type: "text" },
      { name: "as_of_date", label: "Figures verified on", type: "date" },
      { name: "start_date", label: "Plan start date", type: "date" },
    ],
    {
      name: "Recovery plan",
      monthly_income: 0,
      ...Object.fromEntries(allocationFields.map(([key]) => [key, 0])),
      reserve_target: 0,
      reserve_saved: 0,
      score: null,
      as_of_date: null,
      start_date: null,
    },
    ["name", "monthly_income", "as_of_date"],
  ),
  subscriptions: config(
    "recovery_subscriptions",
    "Subscriptions",
    "Subscription",
    [
      { name: "name", label: "Service", type: "text", required: true },
      {
        name: "amount",
        label: "Charge per billing period",
        type: "currency",
        required: true,
      },
      {
        name: "frequency",
        label: "Billing frequency",
        type: "select",
        options: ["monthly", "annual", "quarterly", "weekly", "biweekly"],
        required: true,
      },
      {
        name: "decision",
        label: "Planned decision",
        type: "select",
        options: ["review", "keep", "cancel", "pause"],
        required: true,
      },
      {
        name: "status",
        label: "Confirmed service status",
        type: "select",
        options: ["active", "cancelled", "paused"],
        required: true,
        helper: "Update only after the provider confirms the change.",
      },
      { name: "renewal_date", label: "Next renewal", type: "date" },
      {
        name: "recommendation",
        label: "Source recommendation",
        type: "text",
        fullWidth: true,
      },
    ],
    {
      name: "",
      amount: 0,
      frequency: "monthly",
      decision: "review",
      status: "active",
    },
    ["name", "amount", "frequency", "decision", "status", "renewal_date"],
  ),
  assets: config(
    "financial_assets",
    "Assets",
    "Asset",
    [
      { name: "name", label: "Asset", type: "text", required: true },
      {
        name: "category",
        label: "Category",
        type: "select",
        options: ["cash", "property", "vehicle", "investment", "other"],
        required: true,
      },
      {
        name: "estimated_value",
        label: "Estimated value",
        type: "currency",
        helper: "Leave blank if unknown.",
      },
      {
        name: "debt",
        label: "Debt against this asset",
        type: "currency",
        helper: "Enter 0 only when confirmed debt-free.",
      },
      { name: "as_of_date", label: "Valued on", type: "date" },
    ],
    { name: "", category: "other", estimated_value: null, debt: null },
    ["name", "category", "estimated_value", "debt", "as_of_date"],
  ),
  installments: config(
    "installment_debts",
    "Installment debts",
    "Installment Debt",
    [
      { name: "name", label: "Lender or plan", type: "text", required: true },
      {
        name: "balance",
        label: "Remaining balance",
        type: "currency",
        required: true,
      },
      {
        name: "monthly_payment",
        label: "Monthly payment",
        type: "currency",
        required: true,
      },
      {
        name: "apr",
        label: "APR as decimal",
        type: "currency",
        helper: "For 15%, enter 0.15. Leave blank if unknown.",
      },
      { name: "due_date", label: "Next due date", type: "date" },
    ],
    { name: "", balance: 0, monthly_payment: 0, apr: null },
    ["name", "balance", "monthly_payment", "apr", "due_date"],
  ),
  financeActions: config(
    "finance_actions",
    "Recovery actions",
    "Recovery Action",
    [
      { name: "title", label: "Action", type: "text", required: true },
      {
        name: "phase",
        label: "Phase",
        type: "select",
        options: [
          "today",
          "this_week",
          "this_month",
          "next_90_days",
          "ongoing",
        ],
        required: true,
      },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["not_started", "in_progress", "done"],
        required: true,
      },
      {
        name: "priority",
        label: "Priority",
        type: "select",
        options: ["low", "medium", "high", "urgent"],
        required: true,
      },
      { name: "due_date", label: "Due date", type: "date" },
    ],
    {
      title: "",
      phase: "this_week",
      status: "not_started",
      priority: "medium",
    },
    ["title", "phase", "priority", "status", "due_date"],
  ),
};
