import { addDays, format, setHours, setMinutes, startOfDay, startOfMonth } from "date-fns";
import type { CurrentUser, DataStore } from "@/lib/types";

const familyId = "family_rivera_starter";
const avaId = "member_ava_rivera";
const milesId = "member_miles_rivera";
const lilyId = "member_lily_rivera";
const noahId = "member_noah_rivera";

function isoDate(days: number) {
  return format(addDays(startOfDay(new Date()), days), "yyyy-MM-dd");
}

function isoDateTime(days: number, hour: number, minute = 0) {
  const date = setMinutes(setHours(addDays(startOfDay(new Date()), days), hour), minute);
  return date.toISOString();
}

function stamp(days = -7) {
  return addDays(new Date(), days).toISOString();
}

export const localUser: CurrentUser = {
  id: "user_starter_ava",
  member_id: avaId,
  email: "ava.rivera@example.test",
  display_name: "Ava Rivera",
  role: "admin"
};

export function createSeedData(): DataStore {
  const created = stamp(-24);
  const updated = stamp(-1);
  const budgetMonth = format(startOfMonth(new Date()), "yyyy-MM-dd");

  function currentMonthDate(day: number) {
    const date = startOfMonth(new Date());
    date.setDate(day);
    return format(date, "yyyy-MM-dd");
  }

  return {
    families: [
      {
        id: familyId,
        name: "Rivera Family",
        created_at: created,
        updated_at: updated
      }
    ],
    family_members: [
      {
        id: avaId,
        family_id: familyId,
        user_id: localUser.id,
        display_name: "Ava Rivera",
        role: "admin",
        avatar_url: null,
        phone: "555-0101",
        email: "ava.rivera@example.test",
        relationship: "Mom",
        created_at: created,
        updated_at: updated
      },
      {
        id: milesId,
        family_id: familyId,
        user_id: "user_starter_miles",
        display_name: "Miles Rivera",
        role: "parent",
        avatar_url: null,
        phone: "555-0102",
        email: "miles.rivera@example.test",
        relationship: "Dad",
        created_at: created,
        updated_at: updated
      },
      {
        id: lilyId,
        family_id: familyId,
        user_id: null,
        display_name: "Lily Rivera",
        role: "viewer",
        avatar_url: null,
        phone: null,
        email: null,
        relationship: "Child",
        created_at: created,
        updated_at: updated
      },
      {
        id: noahId,
        family_id: familyId,
        user_id: null,
        display_name: "Noah Rivera",
        role: "viewer",
        avatar_url: null,
        phone: null,
        email: null,
        relationship: "Child",
        created_at: created,
        updated_at: updated
      }
    ],
    events: [
      {
        id: "event_family_dinner",
        family_id: familyId,
        title: "Family dinner",
        description: "Grandma is bringing dessert.",
        category: "Family",
        location: "Home",
        start_at: isoDateTime(0, 18),
        end_at: isoDateTime(0, 19, 30),
        all_day: false,
        recurrence_rule: "Weekly on Tuesday",
        assigned_to: null,
        created_by: avaId,
        created_at: created,
        updated_at: updated
      },
      {
        id: "event_lily_conference",
        family_id: familyId,
        title: "Lily parent-teacher conference",
        description: "Bring reading folder and math packet.",
        category: "School",
        location: "Northview Elementary",
        start_at: isoDateTime(2, 15, 30),
        end_at: isoDateTime(2, 16),
        all_day: false,
        recurrence_rule: null,
        assigned_to: lilyId,
        created_by: avaId,
        created_at: created,
        updated_at: updated
      },
      {
        id: "event_noah_checkup",
        family_id: familyId,
        title: "Noah annual checkup",
        description: "Confirm sports physical form.",
        category: "Medical",
        location: "Harbor Pediatrics",
        start_at: isoDateTime(6, 9),
        end_at: isoDateTime(6, 9, 45),
        all_day: false,
        recurrence_rule: null,
        assigned_to: noahId,
        created_by: milesId,
        created_at: created,
        updated_at: updated
      },
      {
        id: "event_mortgage_due",
        family_id: familyId,
        title: "Mortgage due",
        description: "Autopay scheduled.",
        category: "Bills",
        location: null,
        start_at: isoDateTime(4, 8),
        end_at: null,
        all_day: true,
        recurrence_rule: "Monthly on the 1st",
        assigned_to: milesId,
        created_by: milesId,
        created_at: created,
        updated_at: updated
      }
    ],
    tasks: [
      {
        id: "task_permission_slip",
        family_id: familyId,
        title: "Sign Lily field trip permission slip",
        description: "Return the form in Friday folder.",
        category: "School",
        priority: "urgent",
        status: "in_progress",
        assigned_to: avaId,
        due_at: isoDateTime(-1, 17),
        repeat_rule: null,
        completed_at: null,
        created_by: milesId,
        tags: ["school", "paperwork"],
        notes: "Check the backpack front pocket.",
        created_at: created,
        updated_at: updated
      },
      {
        id: "task_hvac_filter",
        family_id: familyId,
        title: "Replace HVAC filter",
        description: "Use 20x25x1 filter from garage shelf.",
        category: "Home",
        priority: "medium",
        status: "not_started",
        assigned_to: milesId,
        due_at: isoDateTime(3, 10),
        repeat_rule: "Every 90 days",
        completed_at: null,
        created_by: avaId,
        tags: ["maintenance"],
        notes: null,
        created_at: created,
        updated_at: updated
      },
      {
        id: "task_meal_prep",
        family_id: familyId,
        title: "Prep taco bowls",
        description: "Cook rice, chop peppers, portion toppings.",
        category: "Meals",
        priority: "low",
        status: "waiting",
        assigned_to: avaId,
        due_at: isoDateTime(1, 16),
        repeat_rule: null,
        completed_at: null,
        created_by: avaId,
        tags: ["food"],
        notes: null,
        created_at: created,
        updated_at: updated
      },
      {
        id: "task_renew_library",
        family_id: familyId,
        title: "Renew library books",
        description: "Renew online before Saturday.",
        category: "Family",
        priority: "medium",
        status: "done",
        assigned_to: milesId,
        due_at: isoDateTime(2, 12),
        repeat_rule: null,
        completed_at: isoDateTime(-1, 9),
        created_by: avaId,
        tags: ["kids"],
        notes: null,
        created_at: created,
        updated_at: updated
      }
    ],
    grocery_items: [
      {
        id: "grocery_apples",
        family_id: familyId,
        name: "Honeycrisp apples",
        category: "Produce",
        quantity: "6",
        unit: "each",
        store: "Market Basket",
        needed_by: isoDate(1),
        checked: false,
        added_by: avaId,
        created_at: created,
        updated_at: updated
      },
      {
        id: "grocery_milk",
        family_id: familyId,
        name: "Whole milk",
        category: "Dairy",
        quantity: "1",
        unit: "gallon",
        store: "Market Basket",
        needed_by: isoDate(0),
        checked: false,
        added_by: milesId,
        created_at: created,
        updated_at: updated
      },
      {
        id: "grocery_filters",
        family_id: familyId,
        name: "HVAC filters 20x25x1",
        category: "Household",
        quantity: "2",
        unit: "pack",
        store: "Home Supply",
        needed_by: isoDate(3),
        checked: false,
        added_by: milesId,
        created_at: created,
        updated_at: updated
      },
      {
        id: "grocery_yogurt",
        family_id: familyId,
        name: "Kids yogurt cups",
        category: "Baby and Kids",
        quantity: "12",
        unit: "pack",
        store: "Market Basket",
        needed_by: isoDate(1),
        checked: true,
        added_by: avaId,
        created_at: created,
        updated_at: updated
      }
    ],
    meal_plans: [
      {
        id: "meal_taco_bowls",
        family_id: familyId,
        meal_date: isoDate(1),
        meal_type: "Dinner",
        title: "Turkey taco bowls",
        recipe_url: "https://example.com/turkey-taco-bowls",
        ingredients: "Ground turkey, rice, black beans, peppers, avocado, salsa",
        notes: "Make extra rice for lunches.",
        created_at: created,
        updated_at: updated
      },
      {
        id: "meal_oatmeal",
        family_id: familyId,
        meal_date: isoDate(2),
        meal_type: "Breakfast",
        title: "Overnight oats",
        recipe_url: null,
        ingredients: "Oats, milk, berries, chia seeds",
        notes: "Prep two jars the night before.",
        created_at: created,
        updated_at: updated
      }
    ],
    financial_accounts: [
      {
        id: "finance_checking",
        family_id: familyId,
        institution_name: "Harbor Credit Union",
        account_type: "Cash",
        owner_name: "Ava and Miles",
        last_four: "2481",
        website_url: "https://example.com",
        support_phone: "555-0150",
        renewal_date: isoDate(90),
        password_location: "1Password Family Vault",
        notes: "Primary household checking. Do not store full account numbers here.",
        created_at: created,
        updated_at: updated
      },
      {
        id: "finance_card",
        family_id: familyId,
        institution_name: "Summit Rewards",
        account_type: "Credit",
        owner_name: "Miles",
        last_four: "7712",
        website_url: "https://example.com",
        support_phone: "555-0151",
        renewal_date: isoDate(45),
        password_location: "1Password Family Vault",
        notes: "Used for groceries and gas.",
        created_at: created,
        updated_at: updated
      }
    ],
    budget_settings: [
      {
        id: "budget_settings_current",
        family_id: familyId,
        budget_year: new Date().getFullYear(),
        budget_month: budgetMonth,
        starting_cash_available: 1500,
        planned_monthly_income: 6500,
        include_prior_category_balances: true,
        payoff_strategy: "avalanche",
        target_utilization: 0.3,
        excellent_utilization: 0.1,
        high_utilization_alert: 0.5,
        notes: "Starter values based on the workbook setup tab. Replace with household assumptions.",
        created_at: created,
        updated_at: updated
      }
    ],
    budget_categories: [
      {
        id: "budget_category_rent",
        family_id: familyId,
        budget_month: budgetMonth,
        group_name: "Housing",
        category: "Rent / Mortgage",
        need_want_goal: "need",
        monthly_plan: 2500,
        rollover: false,
        prior_balance: 0,
        notes: null,
        created_at: created,
        updated_at: updated
      },
      {
        id: "budget_category_home_maintenance",
        family_id: familyId,
        budget_month: budgetMonth,
        group_name: "Housing",
        category: "Home Maintenance",
        need_want_goal: "need",
        monthly_plan: 150,
        rollover: true,
        prior_balance: 200,
        notes: "Roll unused maintenance dollars forward.",
        created_at: created,
        updated_at: updated
      },
      {
        id: "budget_category_electricity",
        family_id: familyId,
        budget_month: budgetMonth,
        group_name: "Utilities",
        category: "Electricity",
        need_want_goal: "need",
        monthly_plan: 180,
        rollover: false,
        prior_balance: 0,
        notes: null,
        created_at: created,
        updated_at: updated
      },
      {
        id: "budget_category_internet",
        family_id: familyId,
        budget_month: budgetMonth,
        group_name: "Utilities",
        category: "Internet",
        need_want_goal: "need",
        monthly_plan: 85,
        rollover: false,
        prior_balance: 0,
        notes: null,
        created_at: created,
        updated_at: updated
      },
      {
        id: "budget_category_phone",
        family_id: familyId,
        budget_month: budgetMonth,
        group_name: "Utilities",
        category: "Phone",
        need_want_goal: "need",
        monthly_plan: 120,
        rollover: false,
        prior_balance: 0,
        notes: null,
        created_at: created,
        updated_at: updated
      },
      {
        id: "budget_category_car_payment",
        family_id: familyId,
        budget_month: budgetMonth,
        group_name: "Transportation",
        category: "Car Payment",
        need_want_goal: "need",
        monthly_plan: 450,
        rollover: false,
        prior_balance: 0,
        notes: null,
        created_at: created,
        updated_at: updated
      },
      {
        id: "budget_category_fuel",
        family_id: familyId,
        budget_month: budgetMonth,
        group_name: "Transportation",
        category: "Fuel",
        need_want_goal: "need",
        monthly_plan: 220,
        rollover: false,
        prior_balance: 0,
        notes: null,
        created_at: created,
        updated_at: updated
      },
      {
        id: "budget_category_groceries",
        family_id: familyId,
        budget_month: budgetMonth,
        group_name: "Food",
        category: "Groceries",
        need_want_goal: "need",
        monthly_plan: 850,
        rollover: false,
        prior_balance: 0,
        notes: null,
        created_at: created,
        updated_at: updated
      },
      {
        id: "budget_category_restaurants",
        family_id: familyId,
        budget_month: budgetMonth,
        group_name: "Food",
        category: "Restaurants",
        need_want_goal: "want",
        monthly_plan: 260,
        rollover: false,
        prior_balance: 0,
        notes: null,
        created_at: created,
        updated_at: updated
      },
      {
        id: "budget_category_school",
        family_id: familyId,
        budget_month: budgetMonth,
        group_name: "Kids",
        category: "School",
        need_want_goal: "need",
        monthly_plan: 160,
        rollover: true,
        prior_balance: 75,
        notes: "Forms, activity fees, and classroom supplies.",
        created_at: created,
        updated_at: updated
      },
      {
        id: "budget_category_medical",
        family_id: familyId,
        budget_month: budgetMonth,
        group_name: "Health",
        category: "Medical",
        need_want_goal: "need",
        monthly_plan: 175,
        rollover: true,
        prior_balance: 100,
        notes: null,
        created_at: created,
        updated_at: updated
      },
      {
        id: "budget_category_credit_payment",
        family_id: familyId,
        budget_month: budgetMonth,
        group_name: "Debt",
        category: "Credit Card Payment",
        need_want_goal: "goal",
        monthly_plan: 700,
        rollover: false,
        prior_balance: 0,
        notes: "Includes minimums plus extra principal.",
        created_at: created,
        updated_at: updated
      },
      {
        id: "budget_category_emergency_fund",
        family_id: familyId,
        budget_month: budgetMonth,
        group_name: "Savings",
        category: "Emergency Fund",
        need_want_goal: "goal",
        monthly_plan: 500,
        rollover: true,
        prior_balance: 3500,
        notes: null,
        created_at: created,
        updated_at: updated
      },
      {
        id: "budget_category_streaming",
        family_id: familyId,
        budget_month: budgetMonth,
        group_name: "Lifestyle",
        category: "Streaming",
        need_want_goal: "want",
        monthly_plan: 25,
        rollover: false,
        prior_balance: 0,
        notes: null,
        created_at: created,
        updated_at: updated
      }
    ],
    financial_transactions: [
      {
        id: "transaction_paycheck_1",
        family_id: familyId,
        transaction_date: currentMonthDate(1),
        account_name: "Checking",
        transaction_type: "income",
        category: "Paycheck",
        description: "Sample paycheck",
        amount: 3250,
        cleared: true,
        recurring: false,
        owner_name: "Household",
        notes: null,
        tags: ["income"],
        created_by: avaId,
        created_at: created,
        updated_at: updated
      },
      {
        id: "transaction_rent",
        family_id: familyId,
        transaction_date: currentMonthDate(3),
        account_name: "Checking",
        transaction_type: "expense",
        category: "Rent / Mortgage",
        description: "Sample housing payment",
        amount: 2500,
        cleared: true,
        recurring: true,
        owner_name: "Household",
        notes: null,
        tags: ["housing"],
        created_by: milesId,
        created_at: created,
        updated_at: updated
      },
      {
        id: "transaction_groceries",
        family_id: familyId,
        transaction_date: currentMonthDate(4),
        account_name: "Main Visa",
        transaction_type: "expense",
        category: "Groceries",
        description: "Sample grocery trip",
        amount: 185.42,
        cleared: true,
        recurring: false,
        owner_name: "Household",
        notes: null,
        tags: ["food"],
        created_by: avaId,
        created_at: created,
        updated_at: updated
      },
      {
        id: "transaction_fuel",
        family_id: familyId,
        transaction_date: currentMonthDate(5),
        account_name: "Main Visa",
        transaction_type: "expense",
        category: "Fuel",
        description: "Sample fuel",
        amount: 64.2,
        cleared: true,
        recurring: false,
        owner_name: "Household",
        notes: null,
        tags: ["vehicle"],
        created_by: milesId,
        created_at: created,
        updated_at: updated
      },
      {
        id: "transaction_internet",
        family_id: familyId,
        transaction_date: currentMonthDate(6),
        account_name: "Checking",
        transaction_type: "expense",
        category: "Internet",
        description: "Sample internet bill",
        amount: 85,
        cleared: true,
        recurring: true,
        owner_name: "Household",
        notes: null,
        tags: ["utilities"],
        created_by: avaId,
        created_at: created,
        updated_at: updated
      },
      {
        id: "transaction_streaming",
        family_id: familyId,
        transaction_date: currentMonthDate(8),
        account_name: "Main Visa",
        transaction_type: "expense",
        category: "Streaming",
        description: "Streaming bundle",
        amount: 24.99,
        cleared: true,
        recurring: true,
        owner_name: "Household",
        notes: null,
        tags: ["subscription"],
        created_by: avaId,
        created_at: created,
        updated_at: updated
      }
    ],
    credit_cards: [
      {
        id: "credit_card_main_visa",
        family_id: familyId,
        card_name: "Main Visa",
        issuer: "Example Bank",
        owner_name: "Household",
        last_four: "7712",
        current_balance: 4200,
        credit_limit: 10000,
        apr: 0.2199,
        minimum_payment: 140,
        extra_payment: 260,
        statement_day: 5,
        due_day: 22,
        due_date: currentMonthDate(22),
        autopay: true,
        payment_account: "Checking",
        password_location: "1Password Family Vault",
        notes: "Sample card record. Replace with real last four only.",
        created_at: created,
        updated_at: updated
      },
      {
        id: "credit_card_rewards_mastercard",
        family_id: familyId,
        card_name: "Rewards Mastercard",
        issuer: "Example Credit Union",
        owner_name: "Household",
        last_four: "3855",
        current_balance: 1800,
        credit_limit: 6000,
        apr: 0.1899,
        minimum_payment: 65,
        extra_payment: 135,
        statement_day: 10,
        due_day: 25,
        due_date: currentMonthDate(25),
        autopay: true,
        payment_account: "Checking",
        password_location: "1Password Family Vault",
        notes: "Used for rotating rewards categories.",
        created_at: created,
        updated_at: updated
      },
      {
        id: "credit_card_store",
        family_id: familyId,
        card_name: "Store Card",
        issuer: "Example Store",
        owner_name: "Household",
        last_four: "1048",
        current_balance: 650,
        credit_limit: 1500,
        apr: 0.2999,
        minimum_payment: 40,
        extra_payment: 60,
        statement_day: 18,
        due_day: 12,
        due_date: currentMonthDate(12),
        autopay: false,
        payment_account: "Checking",
        password_location: "1Password Family Vault",
        notes: "High APR. Avalanche plan prioritizes this card.",
        created_at: created,
        updated_at: updated
      }
    ],
    sinking_funds: [
      {
        id: "sinking_emergency_fund",
        family_id: familyId,
        goal: "Emergency Fund",
        category: "Financial",
        target_amount: 10000,
        target_date: isoDate(360),
        saved_so_far: 3500,
        planned_monthly: 500,
        notes: "Primary cash buffer.",
        created_at: created,
        updated_at: updated
      },
      {
        id: "sinking_vacation",
        family_id: familyId,
        goal: "Vacation",
        category: "Travel",
        target_amount: 3000,
        target_date: isoDate(270),
        saved_so_far: 600,
        planned_monthly: 250,
        notes: "Summer family trip.",
        created_at: created,
        updated_at: updated
      },
      {
        id: "sinking_home_repairs",
        family_id: familyId,
        goal: "Home Repairs",
        category: "Home",
        target_amount: 2500,
        target_date: isoDate(210),
        saved_so_far: 450,
        planned_monthly: 150,
        notes: "Repairs that should not hit the credit card.",
        created_at: created,
        updated_at: updated
      },
      {
        id: "sinking_holiday_gifts",
        family_id: familyId,
        goal: "Holiday Gifts",
        category: "Family",
        target_amount: 1200,
        target_date: isoDate(90),
        saved_so_far: 300,
        planned_monthly: 300,
        notes: "Gift budget and seasonal expenses.",
        created_at: created,
        updated_at: updated
      },
      {
        id: "sinking_car_maintenance",
        family_id: familyId,
        goal: "Car Maintenance",
        category: "Home",
        target_amount: 1000,
        target_date: isoDate(150),
        saved_so_far: 250,
        planned_monthly: 125,
        notes: "Oil changes, tires, and small repairs.",
        created_at: created,
        updated_at: updated
      }
    ],
    bills: [
      {
        id: "bill_mortgage",
        family_id: familyId,
        name: "Mortgage",
        category: "Mortgage",
        amount: 2150,
        due_day: 1,
        due_date: isoDate(4),
        autopay: true,
        payment_account: "Harbor Credit Union checking ending 2481",
        status: "upcoming",
        notes: "Autopay confirmation usually arrives two days before due date.",
        created_at: created,
        updated_at: updated
      },
      {
        id: "bill_electric",
        family_id: familyId,
        name: "Electric utility",
        category: "Utilities",
        amount: 168.42,
        due_day: 12,
        due_date: isoDate(9),
        autopay: true,
        payment_account: "Summit Rewards ending 7712",
        status: "upcoming",
        notes: "Review high usage months.",
        created_at: created,
        updated_at: updated
      },
      {
        id: "bill_soccer",
        family_id: familyId,
        name: "Noah soccer registration",
        category: "School",
        amount: 95,
        due_day: null,
        due_date: isoDate(-2),
        autopay: false,
        payment_account: "Checking",
        status: "overdue",
        notes: "Pay before roster closes.",
        created_at: created,
        updated_at: updated
      }
    ],
    health_records: [
      {
        id: "health_pediatrician",
        family_id: familyId,
        person_id: noahId,
        record_type: "Provider",
        provider_name: "Harbor Pediatrics",
        provider_phone: "555-0201",
        policy_provider: "Example Health",
        policy_last_four: "4408",
        medication_name: null,
        dosage: null,
        allergy: null,
        condition: null,
        appointment_date: isoDateTime(6, 9),
        notes: "Annual wellness visit and sports physical form.",
        created_at: created,
        updated_at: updated
      },
      {
        id: "health_lily_allergy",
        family_id: familyId,
        person_id: lilyId,
        record_type: "Allergy",
        provider_name: null,
        provider_phone: null,
        policy_provider: null,
        policy_last_four: null,
        medication_name: "Cetirizine",
        dosage: "Children's dose as directed by clinician",
        allergy: "Seasonal pollen",
        condition: null,
        appointment_date: null,
        notes: "Keep allergy note in school backpack during spring.",
        created_at: created,
        updated_at: updated
      }
    ],
    school_records: [
      {
        id: "school_lily",
        family_id: familyId,
        child_id: lilyId,
        school_name: "Northview Elementary",
        grade: "3rd",
        teacher_name: "Ms. Parker",
        teacher_email: "teacher.parker@example.test",
        school_phone: "555-0301",
        pickup_notes: "Grandma Elena is authorized for pickup on Wednesdays.",
        activities: "Art club, reading group",
        important_dates: `Conference ${isoDate(2)}, field trip ${isoDate(12)}`,
        notes: "Check Friday folder each weekend.",
        created_at: created,
        updated_at: updated
      },
      {
        id: "school_noah",
        family_id: familyId,
        child_id: noahId,
        school_name: "Brookside Middle",
        grade: "6th",
        teacher_name: "Mr. Chen",
        teacher_email: "teacher.chen@example.test",
        school_phone: "555-0302",
        pickup_notes: "Bus route 14 most days.",
        activities: "Soccer, robotics",
        important_dates: `Science fair proposal due ${isoDate(8)}`,
        notes: "Needs graph paper for math lab.",
        created_at: created,
        updated_at: updated
      }
    ],
    home_records: [
      {
        id: "home_hvac",
        family_id: familyId,
        category: "HVAC",
        title: "Replace HVAC filter",
        vendor_name: "Cool Air Service",
        vendor_phone: "555-0401",
        warranty_expiration: isoDate(220),
        maintenance_due: isoDate(3),
        location: "Hall closet intake",
        notes: "20x25x1 filters stored in garage.",
        created_at: created,
        updated_at: updated
      },
      {
        id: "home_water_heater",
        family_id: familyId,
        category: "Appliance",
        title: "Water heater flush",
        vendor_name: "Oak Plumbing",
        vendor_phone: "555-0402",
        warranty_expiration: isoDate(600),
        maintenance_due: isoDate(30),
        location: "Garage",
        notes: "Annual flush recommended.",
        created_at: created,
        updated_at: updated
      }
    ],
    vehicle_records: [
      {
        id: "vehicle_van",
        family_id: familyId,
        vehicle_name: "Family minivan",
        vin_last_six: "7H2K91",
        plate: "FAM-204",
        insurance_provider: "Example Mutual",
        policy_last_four: "1904",
        registration_due: isoDate(70),
        maintenance_due: isoDate(14),
        mileage: 68240,
        notes: "Oil change and tire rotation due soon.",
        created_at: created,
        updated_at: updated
      },
      {
        id: "vehicle_sedan",
        family_id: familyId,
        vehicle_name: "Commuter sedan",
        vin_last_six: "92PLQ8",
        plate: "CITY-88",
        insurance_provider: "Example Mutual",
        policy_last_four: "1904",
        registration_due: isoDate(140),
        maintenance_due: isoDate(45),
        mileage: 42120,
        notes: "Wiper blades replaced last month.",
        created_at: created,
        updated_at: updated
      }
    ],
    documents: [
      {
        id: "doc_insurance_cards",
        family_id: familyId,
        title: "Health insurance card copies",
        category: "Insurance",
        file_url: null,
        storage_location: "Family Drive / Insurance / Current Cards",
        renewal_date: isoDate(180),
        owner: "Ava",
        notes: "Upload copies after Supabase Storage is configured.",
        created_at: created,
        updated_at: updated
      },
      {
        id: "doc_school_forms",
        family_id: familyId,
        title: "School forms folder",
        category: "School",
        file_url: null,
        storage_location: "Kitchen command drawer",
        renewal_date: isoDate(60),
        owner: "Miles",
        notes: "Contains field trip and sports forms.",
        created_at: created,
        updated_at: updated
      }
    ],
    contacts: [
      {
        id: "contact_elena",
        family_id: familyId,
        name: "Elena Rivera",
        relationship: "Grandparent",
        category: "Emergency",
        phone: "555-0501",
        email: "elena@example.test",
        address: "12 Maple Street",
        notes: "Authorized school pickup.",
        emergency_contact: true,
        created_at: created,
        updated_at: updated
      },
      {
        id: "contact_pediatrician",
        family_id: familyId,
        name: "Harbor Pediatrics",
        relationship: "Pediatrician",
        category: "Doctor",
        phone: "555-0201",
        email: "frontdesk@example.test",
        address: "100 Harbor Way",
        notes: "After-hours nurse line available.",
        emergency_contact: false,
        created_at: created,
        updated_at: updated
      },
      {
        id: "contact_neighbor",
        family_id: familyId,
        name: "Sam Patel",
        relationship: "Neighbor",
        category: "Neighbor",
        phone: "555-0502",
        email: "sam.patel@example.test",
        address: "Next door",
        notes: "Has spare key for emergencies.",
        emergency_contact: true,
        created_at: created,
        updated_at: updated
      }
    ],
    communication_notes: [
      {
        id: "note_backpack",
        family_id: familyId,
        title: "Check Lily's backpack",
        message: "The field trip form and lunch choice sheet are both in the front pocket.",
        category: "School",
        importance: "high",
        related_date: isoDate(0),
        visible_to: milesId,
        acknowledged_by: [],
        created_by: avaId,
        pinned: true,
        created_at: created,
        updated_at: updated
      },
      {
        id: "note_budget",
        family_id: familyId,
        title: "Budget chat",
        message: "Let's look at summer camp costs after dinner on Thursday.",
        category: "Money",
        importance: "medium",
        related_date: isoDate(2),
        visible_to: null,
        acknowledged_by: [milesId],
        created_by: milesId,
        pinned: false,
        created_at: created,
        updated_at: updated
      }
    ],
    relationship_records: [
      {
        id: "relationship_stress_conversation",
        family_id: familyId,
        title: "Daily stress-reducing conversation",
        category: "Stress",
        practice: "Stress-reducing conversation",
        priority: "high",
        status: "in_progress",
        assigned_to: avaId,
        due_at: isoDateTime(0, 20),
        completed_at: null,
        connection_score: 7,
        partner_a_state: "Carrying work pressure and needs listening without solutions.",
        partner_b_state: "Needs to feel like an ally, not the fixer.",
        positive_interactions: 6,
        negative_interactions: 1,
        cycle_name: "None",
        repair_attempt: "Ask first: do you want empathy or help?",
        next_step: "Take 20 minutes after kids are down. Outside stress only.",
        notes: "Listener takes partner's side and reflects back what they heard.",
        tags: ["gottman", "stress"],
        created_by: avaId,
        created_at: created,
        updated_at: updated
      },
      {
        id: "relationship_weekly_union",
        family_id: familyId,
        title: "Weekly state of the union",
        category: "Check-In",
        practice: "Weekly state of the union",
        priority: "medium",
        status: "not_started",
        assigned_to: milesId,
        due_at: isoDateTime(3, 19),
        completed_at: null,
        connection_score: 6,
        partner_a_state: "Wants a calmer way to raise logistics and fairness.",
        partner_b_state: "Wants one topic at a time and clear requests.",
        positive_interactions: 5,
        negative_interactions: 1,
        cycle_name: "Protest Polka",
        repair_attempt: "Start with appreciations and one issue only.",
        next_step: "Each bring one appreciation and one concrete request.",
        notes: "Use soft startup: I feel X about Y, and I need Z.",
        tags: ["gottman", "check-in"],
        created_by: milesId,
        created_at: created,
        updated_at: updated
      },
      {
        id: "relationship_repair_budget",
        family_id: familyId,
        title: "Repair after budget tension",
        category: "Repair",
        practice: "Repair attempt",
        priority: "high",
        status: "waiting",
        assigned_to: avaId,
        due_at: isoDateTime(1, 12),
        completed_at: null,
        connection_score: 5,
        partner_a_state: "Felt alone holding camp-cost planning.",
        partner_b_state: "Felt criticized and got defensive.",
        positive_interactions: 3,
        negative_interactions: 2,
        cycle_name: "Find the Bad Guy",
        repair_attempt: "Can we restart? I want to understand your pressure before we solve it.",
        next_step: "Name shared goal before numbers: summer plan without resentment.",
        notes: "Watch for defensiveness and switch to responsibility-taking.",
        tags: ["repair", "money"],
        created_by: avaId,
        created_at: created,
        updated_at: updated
      },
      {
        id: "relationship_connection_ritual",
        family_id: familyId,
        title: "Launch and landing ritual",
        category: "Daily Connection",
        practice: "Six-second kiss",
        priority: "low",
        status: "in_progress",
        assigned_to: null,
        due_at: isoDateTime(0, 8),
        completed_at: null,
        connection_score: 8,
        partner_a_state: "Likes morning connection before work mode starts.",
        partner_b_state: "Likes a real hello after commute decompression.",
        positive_interactions: 8,
        negative_interactions: 1,
        cycle_name: "None",
        repair_attempt: "If one of us misses it, ask warmly later instead of scorekeeping.",
        next_step: "Six-second kiss in the morning and hug until relaxed after work.",
        notes: "Tiny ritual, outsized nervous-system payoff.",
        tags: ["tatkin", "ritual"],
        created_by: milesId,
        created_at: created,
        updated_at: updated
      },
      {
        id: "relationship_desire_context",
        family_id: familyId,
        title: "Desire brakes check-in",
        category: "Intimacy",
        practice: "Desire brakes check",
        priority: "medium",
        status: "not_started",
        assigned_to: null,
        due_at: isoDateTime(5, 21),
        completed_at: null,
        connection_score: 6,
        partner_a_state: "Stress and mental load are the main brakes.",
        partner_b_state: "Needs affection without every touch becoming a request.",
        positive_interactions: 4,
        negative_interactions: 1,
        cycle_name: "None",
        repair_attempt: "Name context and pressure gently, then ask what would remove one brake.",
        next_step: "Plan one low-pressure night with affection, no agenda.",
        notes: "Responsive desire is normal. Context matters more than willpower.",
        tags: ["nagoski", "perel", "intimacy"],
        created_by: avaId,
        created_at: created,
        updated_at: updated
      }
    ],
    activity_ideas: [
      {
        id: "activity_son_skill_hour",
        family_id: familyId,
        title: "Saturday skill hour with Noah",
        category: "At Home",
        audience: "son",
        description: "Let Noah pick one practical skill to learn together, then end with a snack and a quick photo for the family album.",
        location: "Home",
        estimated_cost: 10,
        duration_minutes: 75,
        season: "Anytime",
        indoor: true,
        supplies: "Simple project supplies, snack, timer",
        status: "idea",
        scheduled_event_id: null,
        assigned_to: noahId,
        notes: "Good for a low-pressure one-on-one morning.",
        created_by: milesId,
        created_at: created,
        updated_at: updated
      },
      {
        id: "activity_daughter_art_date",
        family_id: familyId,
        title: "Lily art and cocoa date",
        category: "Creative",
        audience: "daughter",
        description: "Bring sketchbooks to the neighborhood cafe, draw for 30 minutes, then each person shares one favorite detail.",
        location: "Neighborhood cafe",
        estimated_cost: 18,
        duration_minutes: 90,
        season: "Rainy Day",
        indoor: true,
        supplies: "Sketchbooks, pencils",
        status: "idea",
        scheduled_event_id: null,
        assigned_to: lilyId,
        notes: "Let Lily choose the drawing prompt.",
        created_by: avaId,
        created_at: created,
        updated_at: updated
      },
      {
        id: "activity_kids_trail_picnic",
        family_id: familyId,
        title: "Trail picnic and photo scavenger list",
        category: "Outdoor",
        audience: "all_kids",
        description: "Pick a short trail, pack sandwiches, and give the kids a five-item photo scavenger list.",
        location: "Riverside trail",
        estimated_cost: 25,
        duration_minutes: 150,
        season: "Spring",
        indoor: false,
        supplies: "Lunch, water, sunscreen, printed list",
        status: "planned",
        scheduled_event_id: null,
        assigned_to: null,
        notes: "Keep it short enough to feel easy.",
        created_by: avaId,
        created_at: created,
        updated_at: updated
      },
      {
        id: "activity_date_bookstore",
        family_id: familyId,
        title: "Bookstore date night",
        category: "Date Night",
        audience: "date_night",
        description: "Each person picks one book the other might like, then compare choices over dessert.",
        location: "Downtown bookstore",
        estimated_cost: 45,
        duration_minutes: 150,
        season: "Anytime",
        indoor: true,
        supplies: "Babysitter confirmed, dinner reservation optional",
        status: "idea",
        scheduled_event_id: null,
        assigned_to: null,
        notes: "Protect this from logistics talk for the first hour.",
        created_by: milesId,
        created_at: created,
        updated_at: updated
      },
      {
        id: "activity_family_breakfast_walk",
        family_id: familyId,
        title: "Breakfast walk downtown",
        category: "Food",
        audience: "family",
        description: "Walk to breakfast, let each person choose one topic card, and stop by the library on the way home.",
        location: "Downtown",
        estimated_cost: 55,
        duration_minutes: 120,
        season: "Summer",
        indoor: false,
        supplies: "Topic cards, library bag",
        status: "idea",
        scheduled_event_id: null,
        assigned_to: null,
        notes: "Best on a morning without sports.",
        created_by: avaId,
        created_at: created,
        updated_at: updated
      }
    ],
    calendar_connections: [
      {
        id: "calendar_google_family",
        family_id: familyId,
        provider: "google",
        calendar_name: "Rivera Family Google Calendar",
        sync_direction: "export",
        sync_status: "setup_required",
        feed_url: null,
        external_calendar_id: null,
        include_events: true,
        include_tasks: true,
        include_bills: true,
        include_appointments: true,
        last_synced_at: null,
        notes: "Use Export ICS now. Add OAuth credentials later for automated Google Calendar sync.",
        created_at: created,
        updated_at: updated
      },
      {
        id: "calendar_apple_family",
        family_id: familyId,
        provider: "apple",
        calendar_name: "Rivera Family Apple Calendar",
        sync_direction: "import",
        sync_status: "setup_required",
        feed_url: null,
        external_calendar_id: null,
        include_events: true,
        include_tasks: false,
        include_bills: false,
        include_appointments: true,
        last_synced_at: null,
        notes: "Import the generated ICS file into Apple Calendar or subscribe to a hosted webcal feed.",
        created_at: created,
        updated_at: updated
      }
    ],
    emergency_plan_items: [
      {
        id: "emergency_meeting",
        family_id: familyId,
        category: "Meeting Location",
        title: "Neighborhood meeting spot",
        details: "Meet by the large sign at the community pool if home is not accessible.",
        location: "Community pool entrance",
        contact_name: null,
        contact_phone: null,
        priority: "high",
        created_at: created,
        updated_at: updated
      },
      {
        id: "emergency_water",
        family_id: familyId,
        category: "Home Shutoff",
        title: "Main water shutoff",
        details: "Blue handle behind the garage utility panel.",
        location: "Garage",
        contact_name: "Oak Plumbing",
        contact_phone: "555-0402",
        priority: "urgent",
        created_at: created,
        updated_at: updated
      },
      {
        id: "emergency_pickup",
        family_id: familyId,
        category: "Kids Pickup",
        title: "Authorized pickup list",
        details: "Parents and Elena Rivera are approved for both schools.",
        location: "School offices",
        contact_name: "Elena Rivera",
        contact_phone: "555-0501",
        priority: "high",
        created_at: created,
        updated_at: updated
      }
    ],
    family_goals: [
      {
        id: "goal_emergency_fund",
        family_id: familyId,
        title: "Build emergency fund",
        category: "Financial",
        target_date: isoDate(180),
        progress: 64,
        status: "in_progress",
        notes: "Automated monthly transfer is active.",
        created_at: created,
        updated_at: updated
      },
      {
        id: "goal_family_hike",
        family_id: familyId,
        title: "Monthly family hike",
        category: "Family",
        target_date: isoDate(30),
        progress: 40,
        status: "in_progress",
        notes: "Pick next trail by Friday.",
        created_at: created,
        updated_at: updated
      },
      {
        id: "goal_home_project",
        family_id: familyId,
        title: "Organize garage shelves",
        category: "Home",
        target_date: isoDate(21),
        progress: 20,
        status: "not_started",
        notes: "Buy two clear bins.",
        created_at: created,
        updated_at: updated
      }
    ],
    notifications: [
      {
        id: "notif_overdue_task",
        family_id: familyId,
        kind: "overdue",
        title: "Permission slip is overdue",
        body: "Sign Lily's field trip form today.",
        entity_type: "tasks",
        entity_id: "task_permission_slip",
        read_at: null,
        created_at: created,
        updated_at: updated
      },
      {
        id: "notif_bill_due",
        family_id: familyId,
        kind: "upcoming_bill",
        title: "Mortgage due soon",
        body: "Autopay is scheduled.",
        entity_type: "bills",
        entity_id: "bill_mortgage",
        read_at: null,
        created_at: created,
        updated_at: updated
      }
    ],
    activity_log: [
      {
        id: "activity_seed",
        family_id: familyId,
        actor_id: avaId,
        action: "seeded",
        entity_type: "workspace",
        entity_id: familyId,
        summary: "Starter workspace was created with sample family records.",
        created_at: created
      }
    ]
  };
}
